import type { Brand } from "./interfaces";

export const mockBrands: Brand[] = [
  {
    id: "gaeulcorp-bf0a7318",
    name: "GaeulCorp",
    description: "Leading technology solutions provider",
    logo: "/logoipsum-1.png",
    founded: 2010,
    website: "https://techcorp.com",
    bio: "Crafting user friendly products aesthetically",
    products: [
      {
        id: "ultrabook-pro-1",
        title: "GaeulCorp Ultrabook Pro",
        description:
          "Experience unparalleled performance with the GaeulCorp Ultrabook Pro. This ultra-lightweight and sleek laptop is designed for seamless productivity, whether you're in the office or on the go. Featuring a long-lasting battery and a vibrant display, it's the perfect companion for modern professionals.",
        price: 1499.99,
        discount: 10,
        icon: "💻",
      },
      {
        id: "4k-pro-monitor-2",
        title: "GaeulCorp 4K Pro Monitor",
        description:
          "Bring your visual work to life with the GaeulCorp 4K Pro Monitor. Its stunning 4K resolution and exceptional color accuracy provide a professional-grade viewing experience, ideal for graphic designers, video editors, and anyone who demands crisp, detailed visuals.",
        price: 799.0,
        discount: 0,
        icon: "🖥️",
      },
      {
        id: "wireless-mouse-3",
        title: "Ergonomic Wireless Mouse",
        description:
          "Designed for comfort and precision, this wireless mouse reduces wrist strain during long work sessions. Its silent click feature and adjustable DPI settings make it a versatile tool for both work and creative tasks, ensuring smooth and uninterrupted workflow.",
        price: 44.99,
        discount: 5,
        icon: "🖱️",
      },
    ],
  },
  {
    id: "stylehub-c7fb61a1",
    name: "StyleHub",
    description: "Premium fashion and lifestyle brand",
    logo: "/logoipsum-2.png",
    founded: 2015,
    website: "https://stylehub.com",
    bio: "The new standard in website design.",
    products: [
      {
        id: "canvas-sneakers-1",
        title: "Classic Canvas Sneakers",
        description: "These timeless canvas sneakers are a staple for any wardrobe. Their minimalist design and breathable fabric provide all-day comfort, making them perfect for a casual day out or a relaxed weekend getaway.",
        price: 74.99,
        discount: 5,
        icon: "👟",
        sizes: ["US 7", "US 8", "US 9", "US 10"],
      },
      {
        id: "leather-backpack-2",
        title: "Minimalist Leather Backpack",
        description:
          "Handcrafted from genuine leather, this minimalist backpack combines style and function. With dedicated compartments for your laptop and essentials, it's an elegant solution for carrying everything you need for work or travel.",
        price: 119.99,
        discount: 15,
        icon: "🎒",
      },
      {
        id: "denim-jacket-3",
        title: "Vintage Denim Jacket",
        description: "This classic vintage-inspired denim jacket is built to last. Its durable fabric and timeless fit make it a versatile layer for any season, adding a touch of effortless cool to your look.",
        price: 94.99,
        discount: 10,
        icon: "🧥",
        sizes: ["S", "M", "L", "XL"],
      },
      {
        id: "graphic-tee-4",
        title: "Graphic Tee 'Sunset City'",
        description: "Stand out with this artistic graphic tee featuring a unique 'Sunset City' print. Made from soft, breathable cotton, it offers a comfortable fit and a fresh style for your everyday adventures.",
        price: 29.5,
        discount: 0,
        icon: "👕",
        sizes: ["S", "M", "L", "XL"],
      },
    ],
  },
  {
    id: "homeessentials-c9aa82f6",
    name: "HomeEssentials",
    description: "Quality home and kitchen products",
    logo: "/logoipsum-3.png",
    founded: 2008,
    website: "https://homeessentials.com",
    bio: "Where comfort and design meet. We make your home beautiful.",
    products: [
      {
        id: "smart-blender-1",
        title: "High-Speed Smart Blender",
        description: "Take your kitchen to the next level with this high-speed smart blender. Equipped with pre-programmed settings for smoothies, soups, and shakes, it makes preparing healthy meals faster and easier than ever before.",
        price: 89.99,
        discount: 10,
        icon: "🥛",
      },
      {
        id: "towel-set-2",
        title: "Premium Turkish Cotton Towel Set",
        description: "Transform your bathroom into a spa-like retreat with this luxurious towel set. Made from 100% Turkish cotton, these towels are exceptionally soft, highly absorbent, and get even softer with every wash.",
        price: 49.99,
        discount: 0,
        icon: "🛁",
      },
      {
        id: "air-fryer-3",
        title: "Digital Air Fryer",
        description: "Enjoy your favorite fried foods with less oil and guilt. This digital air fryer circulates hot air to cook food to a perfect crispy finish, offering a healthier way to prepare meals for the whole family.",
        price: 109.99,
        discount: 15,
        icon: "🍟",
      },
      {
        id: "coffee-maker-4",
        title: "Single-Serve Coffee Maker",
        description: "Brew a perfect, personalized cup of coffee in less than a minute. This compact single-serve coffee maker is a great space-saver for small kitchens or dorms and is compatible with a wide range of coffee pods.",
        price: 74.99,
        discount: 10,
        icon: "☕",
      },
      {
        id: "cutlery-set-5",
        title: "Stainless Steel Cutlery Set",
        description:
          "Elevate your dining experience with this elegant and durable cutlery set. Crafted from high-quality stainless steel, each piece is designed to be well-balanced and comfortable to hold, perfect for both everyday use and special occasions.",
        price: 39.5,
        discount: 0,
        icon: "🍴",
      },
      {
        id: "storage-containers-6",
        title: "Glass Food Storage Containers",
        description: "Keep your food fresh and organized with these premium glass food storage containers. They are airtight, microwave-safe, and dishwasher-safe, providing a safe and eco-friendly alternative to plastic containers.",
        price: 24.99,
        discount: 5,
        icon: "🥡",
      },
    ],
  },
  {
    id: "sportmax-f2cfc0fb",
    name: "SportMax",
    description: "Professional sports equipment and gear",
    logo: "/logoipsum-4.png",
    founded: 2012,
    website: "https://sportmax.com",
    bio: "Unleash your potential. Our gear is built for champions.",
    products: [
      {
        id: "adjustable-dumbbell-1",
        title: "Adjustable Dumbbell Set",
        description:
          "Maximize your workout space with this compact and highly versatile adjustable dumbbell set. Quickly change weights with a simple turn of a dial, allowing you to seamlessly transition between exercises and build strength efficiently.",
        price: 149.99,
        discount: 20,
        icon: "🏋️",
      },
      {
        id: "yoga-mat-2",
        title: "Anti-Slip Yoga Mat",
        description: "Find your balance and stability with this anti-slip yoga mat. Its superior grip ensures you can hold your poses with confidence, while the cushioned material provides comfort for your joints during practice.",
        price: 34.99,
        discount: 0,
        icon: "🧘",
      },
      {
        id: "running-shoes-3",
        title: "Lightweight Running Shoes",
        description: "Hit the ground running with these lightweight shoes designed for maximum comfort and performance. The cushioned sole absorbs impact, and the breathable fabric keeps your feet cool, so you can go the distance.",
        price: 109.99,
        discount: 10,
        icon: "👟",
        sizes: ["US 8", "US 9", "US 10", "US 11"],
      },
      {
        id: "fitness-tracker-4",
        title: "Smart Fitness Tracker",
        description: "Stay on top of your health goals with this smart fitness tracker. It monitors your heart rate, tracks your steps, counts calories burned, and provides insights to help you live a more active and healthier life.",
        price: 59.99,
        discount: 5,
        icon: "⌚",
      },
      {
        id: "resistance-bands-5",
        title: "Resistance Bands Set",
        description: "Perfect for a full-body workout at home or in the gym. This versatile set of resistance bands comes with various tension levels, allowing you to target different muscle groups and progress at your own pace.",
        price: 19.99,
        discount: 0,
        icon: "💪",
      },
      {
        id: "protein-powder-6",
        title: "Whey Protein Powder",
        description: "Accelerate your muscle recovery and growth with our high-quality whey protein powder. It's packed with essential amino acids and comes in a delicious chocolate flavor, making it the perfect post-workout shake.",
        price: 44.99,
        discount: 10,
        icon: "🥤",
      },
      {
        id: "jump-rope-7",
        title: "Adjustable Speed Jump Rope",
        description: "Improve your cardio and coordination with this adjustable speed jump rope. The lightweight handles and smooth rotation allow for fast, fluid movements, making it an excellent tool for a quick and effective workout.",
        price: 14.99,
        discount: 0,
        icon: "🤸",
      },
    ],
  },
  {
    id: "ecogreen-a641911c",
    name: "EcoGreen",
    description: "Sustainable and eco-friendly products",
    logo: "/logoipsum-5.png",
    founded: 2018,
    website: "https://ecogreen.com",
    bio: "Sustainable living, stylishly designed. Good for you, better for the planet.",
    products: [
      {
        id: "reusable-bottle-1",
        title: "Bamboo Reusable Water Bottle",
        description: "Stay hydrated and help the planet with our stylish bamboo reusable water bottle. It's made from sustainable materials and features a double-wall design to keep your drinks hot or cold for hours.",
        price: 24.5,
        discount: 0,
        icon: "💧",
      },
      {
        id: "cotton-tote-bag-2",
        title: "Organic Cotton Tote Bag",
        description: "Say no to plastic bags with this durable and spacious organic cotton tote. Perfect for groceries, books, or everyday use, it's a fashionable and eco-friendly choice that you can reuse over and over.",
        price: 17.99,
        discount: 5,
        icon: "🛍️",
      },
      {
        id: "bamboo-toothbrush-3",
        title: "Biodegradable Bamboo Toothbrush",
        description: "Make a small but impactful change to your daily routine with our biodegradable bamboo toothbrush. Its soft bristles provide a gentle clean, and the handle is made from sustainably sourced bamboo.",
        price: 4.99,
        discount: 0,
        icon: "🦷",
      },
    ],
  },
  {
    id: "digitalpro-3430f783",
    name: "DigitalPro",
    description: "Professional digital tools and software",
    logo: "",
    founded: 2014,
    website: "https://digitalpro.com",
    bio: "Your creative partner in the digital age. Powering your next big idea.",
    products: [],
  },
  {
    id: "wellnessplus-0a72a8a3",
    name: "WellnessPlus",
    description: "Health and wellness products",
    logo: "",
    founded: 2016,
    website: "https://wellnessplus.com",
    bio: "Your daily dose of well-being. Simple products for a healthier life.",
    products: [
      {
        id: "vitamin-c-gummies-1",
        title: "Vitamin C Gummies",
        description: "Boost your immune system and enjoy a delicious treat with these Vitamin C gummies. Made with natural flavors, they are an easy and tasty way to get your daily dose of essential nutrients.",
        price: 14.99,
        discount: 0,
        icon: "💊",
      },
      {
        id: "essential-oil-diffuser-2",
        title: "Essential Oil Diffuser",
        description:
          "Create a calming and relaxing atmosphere in your home with our ultrasonic essential oil diffuser. Its silent operation and automatic shut-off feature make it safe and perfect for aromatherapy and humidifying small spaces.",
        price: 29.99,
        discount: 10,
        icon: "🌿",
      },
      {
        id: "yoga-block-3",
        title: "Cork Yoga Block",
        description: "Enhance your yoga practice with this firm and sustainable cork yoga block. It provides the perfect support and stability for holding difficult poses and improving your alignment.",
        price: 11.99,
        discount: 0,
        icon: "🧱",
      },
      {
        id: "massage-gun-4",
        title: "Mini Massage Gun",
        description: "Relieve muscle tension and soreness on the go with this compact and powerful mini massage gun. It's lightweight and easy to carry, making it perfect for post-workout recovery or a quick massage anytime, anywhere.",
        price: 79.99,
        discount: 15,
        icon: "💆",
      },
      {
        id: "sleep-mask-5",
        title: "Silk Sleep Mask",
        description: "Achieve a deeper, more restful sleep with this luxurious silk sleep mask. It gently blocks out all light and feels incredibly soft on your skin, helping you wake up feeling refreshed and revitalized.",
        price: 19.99,
        discount: 5,
        icon: "😴",
      },
    ],
  },
  {
    id: "autotech-33b6924b",
    name: "AutoTech",
    description: "Automotive technology and accessories",
    logo: "",
    founded: 2011,
    website: "https://autotech.com",
    bio: "Driving the future. Innovations that make your ride smarter and safer.",
    products: [
      {
        id: "dash-cam-pro-1",
        title: "Dash Cam Pro",
        description:
          "Drive with confidence with the Dash Cam Pro. This high-resolution camera records everything on the road, providing critical evidence in case of an accident. It features a wide-angle lens, night vision, and a G-sensor for automatic incident detection.",
        price: 99.99,
        discount: 10,
        icon: "📹",
      },
      {
        id: "fast-car-charger-2",
        title: "Fast Car Charger",
        description:
          "Keep your devices powered up on the road with this fast car charger. Equipped with dual USB ports and intelligent charging technology, it delivers a high-speed charge to your phone, tablet, and other gadgets, so you're always connected.",
        price: 19.99,
        discount: 0,
        icon: "🚗",
      },
    ],
  },
];
